### ISSUE TITLE
ESLint error when following install instructions

### ISSUE THREAD

**Issue by sselfridge** [markcheno/go-vue-starter#7]
Attempting to learn VUE + Go + Docker for a take home assignment, thought this would be great but I'm unable to get the front end running.  Followed install instructions, but this is what I'm getting when I run 'npm run dev'

`> starter@1.0.0 dev ~/go/src/github.com/markcheno/go-vue-starter/client
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://localhost:3000/api
[HPM] Proxy rewrite rule created: "^/api" ~> ""
> Starting dev server...

 ERROR  Failed to compile with 1 errors                                                                                                           6:05:04 PM

 error  in ./src/main.js

Module build failed: Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint-plugin-html/src/index.js:65:11)
    at Object.<anonymous> (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint-plugin-html/src/index.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Plugins.load (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config/plugins.js:101:26)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config/plugins.js:146:21)
    at loadFromDisk (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config/config-file.js:492:35)
    at Object.load (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/samwise/go/src/github.com/markcheno/go-vue-starter/client/node_modules/eslint/lib/config.js:180:43)

 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080
`

Googling seems to be a eslint-plugin-html version issue, and forcefully upgrading it to 6.0.0 still has things failing with specific lint errors.   Got some warnings about needing to upgrade webpack at the same time.  Have a feeling this is a pretty basic error when you've use this env before, but as everything is completely new I'm lost.

Backend seems to be running ok.

**Comment by markcheno** [comment]
Should be fixed now. Thanks for the heads up. Clone the latest version and start over and you should be good.

**Comment by sselfridge** [comment]
Works now! Thanks for the Prompt fix!
